# 参考: https://github.com/snyk-labs/nodejs-goof/blob/f985f27f48b00b38c0d2d86f87280bee06fddb0c/.github/workflows/snyk-code.yml#L1
name: "snyk code test"
on: [push]
jobs:
  snyk_code_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk code test --org=${{ secrets.SNYK_ORG }}
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
